#db:
#  image: rethinkdb
#  ports:
#    - "8080:8080"
#user-api:
#    build: .
#    command: npm run user-api
#    ports:
#      - "4000:4000"
#    volumes:
#      - .:/opt/app
#    links:
#      - db:rethinkdb.tetris-solutions.com.br
web:
  build: .
  command: npm run start
  volumes:
    - ./src:/opt/app/src
  ports:
    - "3000:3000"
#  links:
#    - user-api:user.api.tetris-solutions.com.br

