db:
  image: rethinkdb
  ports:
    - "8080:8080"
user-api:
    build: .
    dockerfile: Dockerfile-api
    command: npm run user-api
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    links:
      - db:rethinkdb.tetris-solutions.com.br
web:
  build: .
  command: npm run start-dev
  environment:
    NODE_ENV: development
  volumes:
    - .:/code
  ports:
    - "3000:3000"
  links:
    - user-api:user.api.tetris-solutions.com.br

