db:
  image: postgres
  environment:
    POSTGRES_USER: ${BASE_DB_USER}
    POSTGRES_PASSWORD: ${BASE_DB_PWD}
  ports:
    - "5432:5432"
user-api:
    build: .
    env_file: .env.docker
    command: npm run user-api
    ports:
      - "4000:4000"
    links:
      - "db:${BASE_DB_HOST}"
web:
  build: .
  env_file: .env.docker
  command: npm run start
  volumes:
    - ./src:/opt/app/src
    - ./node_modules:/opt/app/node_modules
  ports:
    - "3000:3000"
  links:
    - "user-api:${USER_API_HOST}"
