db:
  image: rethinkdb
  ports:
    - "8080:8080"
user-api:
    build: .
    command: npm run user-api
    volumes:
      - .:/opt/app/src
    ports:
      - "4000:4000"
    links:
      - "db:${RETHINKDB_HOST}"
web:
  build: .
  command: npm run start
  volumes:
    - .:/opt/app/src
  ports:
    - "3000:3000"
  links:
    - "user-api:${USER_API_HOST}"
