version: "3"
services:
  app-main-front:
    environment:
      NPM_TOKEN: ${NPM_TOKEN}
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.node
    volumes:
      - ./:/usr/app
    networks:
      - tetris-odash
networks: 
  tetris-odash:
    external:
      name: tetris-odash_default