FROM node:12.22-alpine

RUN apk add g++ make python3

WORKDIR /usr/app

COPY package.json ./
RUN printf '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > /root/.npmrc

EXPOSE 3000

CMD npm install --production=false && npm run compile && npm run bundle && npm run start
